[features]
seeds = true
skip-lint = false

[programs.localnet]
libreplex_migrator="migr1m1An7f3X75nKuuUn9mm3844miK62ZohpqRfQHp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/devnet-test1.json"

[test]
startup_wait = 100000

[test.validator]
url = "https://api.devnet.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/**/**/tests/**/*.ts"
